trigger:
- master
- feature/*

variables:
  version: "1.0.0"
  
name: $(version)-$(Date:yyyyMMdd)$(Rev:.rrr)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Installing .NET Core 3 SDK'
  inputs:
    packageType: 'sdk'
    version: '3.0.100-rc1-014190'
    includePreviewVersions: true

- script: dotnet build -c Release
  displayName: 'Build solution'

- script: dotnet publish BlazorPresentationDemo/BlazorPresentationDemo.csproj -c Release -r win10-x86 --self-contained true
  displayName: 'Publish Blazor Server site'

- script: dotnet publish BlazorPresentationDemo.WebAssembly/BlazorPresentationDemo.WebAssembly.csproj -c Release
  displayName: 'Publish Blazor WebAssembly site'

- task: ArchiveFiles@2
  displayName: 'Create deployment package for Blazor Server site'
  inputs:
    rootFolderOrFile: 'BlazorPresentationDemo/bin/Release/netcoreapp3.0/win10-x86/publish'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/blazorserver/BlazorPresentationDemo-$(Build.BuildNumber).zip'

- task: ArchiveFiles@2
  displayName: 'Create deployment package for Blazor WASM site'
  inputs:
    rootFolderOrFile: 'BlazorPresentationDemo.WebAssembly/bin/Release/netstandard2.0/publish/BlazorPresentationDemo.WebAssembly/dist'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/blazorwasm/BlazorPresentationDemo-WebAssembly-$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 